# Generated by Django 4.1.5 on 2023-07-15 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_interview_tag_alter_post_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='interview',
            old_name='tag',
            new_name='tags',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='tag',
            new_name='tags',
        ),
    ]
